CREATE TYPE "public"."categoria_template" AS ENUM('marketing', 'utilidade', 'autenticacao', 'servico');--> statement-breakpoint
CREATE TYPE "public"."etapa_funil" AS ENUM('em_conversa', 'interessado', 'fechando', 'fechou', 'nao_fechou');--> statement-breakpoint
CREATE TYPE "public"."etapa_kanban" AS ENUM('agendada', 'na-fila', 'enviando', 'concluida', 'com-falhas', 'falhou');--> statement-breakpoint
CREATE TYPE "public"."etapa_origem" AS ENUM('ia', 'manual');--> statement-breakpoint
CREATE TYPE "public"."motivo_perda" AS ENUM('preco', 'fidelidade', 'localizacao', 'horario', 'sem_interesse', 'sumiu', 'ja_aluno', 'outro');--> statement-breakpoint
CREATE TYPE "public"."papel_usuario" AS ENUM('admin', 'membro');--> statement-breakpoint
CREATE TYPE "public"."status_campanha" AS ENUM('agendada', 'enviando', 'concluida');--> statement-breakpoint
CREATE TYPE "public"."status_envio" AS ENUM('pendente', 'enviado', 'falhou');--> statement-breakpoint
CREATE TYPE "public"."tipo_mensagem" AS ENUM('texto', 'audio', 'figurinha');--> statement-breakpoint
CREATE TYPE "public"."status_sugestao_ia" AS ENUM('pendente', 'enviada', 'descartada');--> statement-breakpoint
CREATE TABLE "templates_whatsapp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "templates_whatsapp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conta_id" integer,
	"nome" varchar(255) NOT NULL,
	"conteudo" text NOT NULL,
	"categoria" "categoria_template" DEFAULT 'marketing' NOT NULL,
	"idioma" varchar(15) DEFAULT 'pt_BR' NOT NULL,
	"cabecalho_imagem_url" varchar(1024),
	"cabecalho_formato" varchar(20),
	"cabecalho_texto" varchar(255),
	"rodape" varchar(255),
	"meta_id" varchar(40),
	"status" varchar(20) DEFAULT 'APPROVED' NOT NULL,
	"motivo_status" varchar(500),
	"ativo" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campanhas_disparo" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "campanhas_disparo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(255) NOT NULL,
	"template_id" integer NOT NULL,
	"numero_id" integer,
	"status" "status_campanha" DEFAULT 'enviando' NOT NULL,
	"disparo_em" timestamp with time zone DEFAULT now() NOT NULL,
	"etapa_manual" "etapa_kanban",
	"custo_unitario" numeric(10, 4),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "disparo_destinatarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "disparo_destinatarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campanha_id" integer NOT NULL,
	"telefone" varchar(20) NOT NULL,
	"parametros" jsonb NOT NULL,
	"status_envio" "status_envio" DEFAULT 'pendente' NOT NULL,
	"tentativas" integer DEFAULT 0 NOT NULL,
	"erro_detalhe" text,
	"enviado_em" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "respostas_clientes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "respostas_clientes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mensagem_externa_id" varchar(191),
	"telefone" varchar(20) NOT NULL,
	"numero_id" integer,
	"campanha_id" integer,
	"destinatario_id" integer,
	"tipo" "tipo_mensagem" DEFAULT 'texto' NOT NULL,
	"texto" text NOT NULL,
	"midia_url" varchar(500),
	"midia_mime_type" varchar(100),
	"recebida_em" timestamp with time zone NOT NULL,
	"lida_em" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mensagens_saida" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mensagens_saida_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"telefone" varchar(20) NOT NULL,
	"numero_id" integer,
	"tipo" "tipo_mensagem" DEFAULT 'texto' NOT NULL,
	"texto" text NOT NULL,
	"midia_url" varchar(500),
	"midia_mime_type" varchar(100),
	"status_envio" "status_envio" DEFAULT 'pendente' NOT NULL,
	"tentativas" integer DEFAULT 0 NOT NULL,
	"erro_detalhe" text,
	"mensagem_externa_id" varchar(191),
	"enviado_em" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conversas_config" (
	"telefone" varchar(20) PRIMARY KEY NOT NULL,
	"numero_id" integer,
	"ia_ativa" boolean DEFAULT false NOT NULL,
	"precisa_humano" boolean DEFAULT false NOT NULL,
	"motivo_humano" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contatos" (
	"telefone" varchar(20) PRIMARY KEY NOT NULL,
	"nome_perfil" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sugestoes_ia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sugestoes_ia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"telefone" varchar(20) NOT NULL,
	"numero_id" integer,
	"texto" text NOT NULL,
	"status" "status_sugestao_ia" DEFAULT 'pendente' NOT NULL,
	"resposta_cliente_id" integer,
	"modelo" varchar(64) NOT NULL,
	"tokens_entrada" integer DEFAULT 0 NOT NULL,
	"tokens_saida" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sessoes" (
	"token" varchar(64) PRIMARY KEY NOT NULL,
	"usuario_id" integer NOT NULL,
	"expira_em" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usuarios" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuarios_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"email" varchar(255) NOT NULL,
	"senha_hash" varchar(255) NOT NULL,
	"papel" "papel_usuario" DEFAULT 'membro' NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "usuarios_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "configuracoes" (
	"chave" varchar(60) PRIMARY KEY NOT NULL,
	"valor" text NOT NULL,
	"secreto" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "contas_whatsapp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contas_whatsapp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"waba_id" varchar(40) NOT NULL,
	"token_cifrado" text NOT NULL,
	"token_final" varchar(8) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contas_whatsapp_waba_id_unique" UNIQUE("waba_id")
);
--> statement-breakpoint
CREATE TABLE "numeros_whatsapp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "numeros_whatsapp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conta_id" integer NOT NULL,
	"phone_number_id" varchar(40) NOT NULL,
	"numero_exibicao" varchar(32) NOT NULL,
	"nome_verificado" varchar(120),
	"qualidade" varchar(20),
	"ativo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "numeros_whatsapp_phone_number_id_unique" UNIQUE("phone_number_id")
);
--> statement-breakpoint
CREATE TABLE "duvidas_ia" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "duvidas_ia_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"telefone" varchar(20) NOT NULL,
	"numero_id" integer NOT NULL,
	"tema" varchar(120) NOT NULL,
	"pergunta" varchar(500) NOT NULL,
	"sanada" boolean NOT NULL,
	"perguntada_em" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "funil_clientes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "funil_clientes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"telefone" varchar(20) NOT NULL,
	"numero_id" integer NOT NULL,
	"etapa" "etapa_funil" DEFAULT 'em_conversa' NOT NULL,
	"etapa_origem" "etapa_origem" DEFAULT 'ia' NOT NULL,
	"motivo_perda" "motivo_perda",
	"motivo_detalhe" varchar(500),
	"resumo" varchar(1000),
	"proximo_passo" varchar(300),
	"analisado_em" timestamp with time zone,
	"ultima_mensagem_analisada" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "templates_whatsapp" ADD CONSTRAINT "templates_whatsapp_conta_id_contas_whatsapp_id_fk" FOREIGN KEY ("conta_id") REFERENCES "public"."contas_whatsapp"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campanhas_disparo" ADD CONSTRAINT "campanhas_disparo_template_id_templates_whatsapp_id_fk" FOREIGN KEY ("template_id") REFERENCES "public"."templates_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campanhas_disparo" ADD CONSTRAINT "campanhas_disparo_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "disparo_destinatarios" ADD CONSTRAINT "disparo_destinatarios_campanha_id_campanhas_disparo_id_fk" FOREIGN KEY ("campanha_id") REFERENCES "public"."campanhas_disparo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "respostas_clientes" ADD CONSTRAINT "respostas_clientes_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "respostas_clientes" ADD CONSTRAINT "respostas_clientes_campanha_id_campanhas_disparo_id_fk" FOREIGN KEY ("campanha_id") REFERENCES "public"."campanhas_disparo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "respostas_clientes" ADD CONSTRAINT "respostas_clientes_destinatario_id_disparo_destinatarios_id_fk" FOREIGN KEY ("destinatario_id") REFERENCES "public"."disparo_destinatarios"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mensagens_saida" ADD CONSTRAINT "mensagens_saida_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversas_config" ADD CONSTRAINT "conversas_config_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sugestoes_ia" ADD CONSTRAINT "sugestoes_ia_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessoes" ADD CONSTRAINT "sessoes_usuario_id_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "numeros_whatsapp" ADD CONSTRAINT "numeros_whatsapp_conta_id_contas_whatsapp_id_fk" FOREIGN KEY ("conta_id") REFERENCES "public"."contas_whatsapp"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duvidas_ia" ADD CONSTRAINT "duvidas_ia_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "funil_clientes" ADD CONSTRAINT "funil_clientes_numero_id_numeros_whatsapp_id_fk" FOREIGN KEY ("numero_id") REFERENCES "public"."numeros_whatsapp"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "disparo_destinatarios_campanha_telefone_unique" ON "disparo_destinatarios" USING btree ("campanha_id","telefone");--> statement-breakpoint
CREATE UNIQUE INDEX "respostas_clientes_mensagem_externa_unique" ON "respostas_clientes" USING btree ("mensagem_externa_id");--> statement-breakpoint
CREATE INDEX "respostas_clientes_campanha_idx" ON "respostas_clientes" USING btree ("campanha_id");--> statement-breakpoint
CREATE INDEX "respostas_clientes_telefone_idx" ON "respostas_clientes" USING btree ("telefone","recebida_em");--> statement-breakpoint
CREATE INDEX "respostas_clientes_recebida_em_idx" ON "respostas_clientes" USING btree ("recebida_em");--> statement-breakpoint
CREATE INDEX "mensagens_saida_telefone_idx" ON "mensagens_saida" USING btree ("telefone","created_at");--> statement-breakpoint
CREATE INDEX "sugestoes_ia_telefone_status" ON "sugestoes_ia" USING btree ("telefone","status");--> statement-breakpoint
CREATE INDEX "sessoes_usuario" ON "sessoes" USING btree ("usuario_id");--> statement-breakpoint
CREATE INDEX "numeros_whatsapp_conta" ON "numeros_whatsapp" USING btree ("conta_id");--> statement-breakpoint
CREATE INDEX "duvidas_ia_conversa" ON "duvidas_ia" USING btree ("numero_id","telefone");--> statement-breakpoint
CREATE INDEX "duvidas_ia_periodo" ON "duvidas_ia" USING btree ("perguntada_em");--> statement-breakpoint
CREATE UNIQUE INDEX "funil_clientes_conversa" ON "funil_clientes" USING btree ("numero_id","telefone");