-- Unidades: cada academia tem o próprio painel. Tudo o que já existia vira da primeira unidade, e o
-- primeiro administrador vira o superadmin (dono da plataforma, sem unidade).

-- Papel "superadmin". Recria o tipo em vez de ADD VALUE: um valor novo de enum não pode ser usado na
-- mesma transação em que foi criado, e o UPDATE mais abaixo usa.
ALTER TABLE "usuarios" ALTER COLUMN "papel" DROP DEFAULT;--> statement-breakpoint
ALTER TYPE "public"."papel_usuario" RENAME TO "papel_usuario_antigo";--> statement-breakpoint
CREATE TYPE "public"."papel_usuario" AS ENUM('superadmin', 'admin', 'membro');--> statement-breakpoint
ALTER TABLE "usuarios" ALTER COLUMN "papel" TYPE "public"."papel_usuario" USING "papel"::text::"public"."papel_usuario";--> statement-breakpoint
ALTER TABLE "usuarios" ALTER COLUMN "papel" SET DEFAULT 'membro';--> statement-breakpoint
DROP TYPE "public"."papel_usuario_antigo";--> statement-breakpoint

CREATE TABLE "unidades" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "unidades_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nome" varchar(120) NOT NULL,
	"ativo" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint
ALTER TABLE "unidades" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
INSERT INTO "unidades" ("nome") VALUES ('Allp Fit');--> statement-breakpoint

-- Colunas novas: entram nulas, recebem a primeira unidade e só então ficam obrigatórias.
ALTER TABLE "usuarios" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "usuarios" ADD COLUMN "disponivel" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "usuarios" ADD COLUMN "disponivel_desde" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "usuarios" ADD COLUMN "ultima_atribuicao_em" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "sessoes" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "contas_whatsapp" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "numeros_whatsapp" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "templates_whatsapp" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "campanhas_disparo" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "midias_agente" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "configuracoes" ADD COLUMN "unidade_id" integer;--> statement-breakpoint
ALTER TABLE "conversas_config" ADD COLUMN "atendente_id" integer;--> statement-breakpoint
ALTER TABLE "conversas_config" ADD COLUMN "atendimento_desde" timestamp with time zone;--> statement-breakpoint

UPDATE "usuarios" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "usuarios" SET "papel" = 'superadmin', "unidade_id" = NULL
	WHERE "id" = (SELECT min("id") FROM "usuarios" WHERE "papel" = 'admin');--> statement-breakpoint
-- O superadmin começa já dentro da unidade existente, para continuar de onde estava.
UPDATE "sessoes" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "contas_whatsapp" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "numeros_whatsapp" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "templates_whatsapp" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "campanhas_disparo" SET "unidade_id" = 1;--> statement-breakpoint
UPDATE "midias_agente" SET "unidade_id" = 1;--> statement-breakpoint
-- A situação da análise diária é da plataforma inteira; o resto (webhook, agente, chave) é da unidade.
UPDATE "configuracoes" SET "unidade_id" = 1 WHERE "chave" NOT LIKE 'analise.%';--> statement-breakpoint

ALTER TABLE "contas_whatsapp" ALTER COLUMN "unidade_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "numeros_whatsapp" ALTER COLUMN "unidade_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "templates_whatsapp" ALTER COLUMN "unidade_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "campanhas_disparo" ALTER COLUMN "unidade_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "midias_agente" ALTER COLUMN "unidade_id" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "configuracoes" DROP CONSTRAINT "configuracoes_pkey";--> statement-breakpoint
ALTER TABLE "configuracoes" ADD COLUMN "id" integer PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY (sequence name "configuracoes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "configuracoes" ADD CONSTRAINT "configuracoes_unidade_chave" UNIQUE NULLS NOT DISTINCT("unidade_id","chave");--> statement-breakpoint
ALTER TABLE "midias_agente" DROP CONSTRAINT "midias_agente_pkey";--> statement-breakpoint
ALTER TABLE "midias_agente" ADD CONSTRAINT "midias_agente_unidade_id_chave_pk" PRIMARY KEY("unidade_id","chave");--> statement-breakpoint

ALTER TABLE "templates_whatsapp" ADD CONSTRAINT "templates_whatsapp_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campanhas_disparo" ADD CONSTRAINT "campanhas_disparo_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversas_config" ADD CONSTRAINT "conversas_config_atendente_id_usuarios_id_fk" FOREIGN KEY ("atendente_id") REFERENCES "public"."usuarios"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessoes" ADD CONSTRAINT "sessoes_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuarios" ADD CONSTRAINT "usuarios_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "configuracoes" ADD CONSTRAINT "configuracoes_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contas_whatsapp" ADD CONSTRAINT "contas_whatsapp_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "midias_agente" ADD CONSTRAINT "midias_agente_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "numeros_whatsapp" ADD CONSTRAINT "numeros_whatsapp_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "conversas_config_atendente" ON "conversas_config" USING btree ("atendente_id");--> statement-breakpoint
CREATE INDEX "usuarios_unidade" ON "usuarios" USING btree ("unidade_id");--> statement-breakpoint
CREATE INDEX "numeros_whatsapp_unidade" ON "numeros_whatsapp" USING btree ("unidade_id");
