CREATE TABLE "contas_instagram" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contas_instagram_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unidade_id" integer NOT NULL,
	"ig_user_id" varchar(40) NOT NULL,
	"username" varchar(100) NOT NULL,
	"nome" varchar(150),
	"foto_url" varchar(1000),
	"token_cifrado" text NOT NULL,
	"token_expira_em" timestamp with time zone,
	"ultima_coleta_em" timestamp with time zone,
	"erro_coleta" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "contas_instagram_unidade_id_unique" UNIQUE("unidade_id"),
	CONSTRAINT "contas_instagram_ig_user_id_unique" UNIQUE("ig_user_id")
);
--> statement-breakpoint
CREATE TABLE "instagram_metricas_diarias" (
	"conta_id" integer NOT NULL,
	"dia" date NOT NULL,
	"seguidores" integer,
	"metricas" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "instagram_metricas_diarias_conta_id_dia_pk" PRIMARY KEY("conta_id","dia")
);
--> statement-breakpoint
ALTER TABLE "contas_instagram" ADD CONSTRAINT "contas_instagram_unidade_id_unidades_id_fk" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "instagram_metricas_diarias" ADD CONSTRAINT "instagram_metricas_diarias_conta_id_contas_instagram_id_fk" FOREIGN KEY ("conta_id") REFERENCES "public"."contas_instagram"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contas_instagram" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "instagram_metricas_diarias" ENABLE ROW LEVEL SECURITY;
